version: '3.8'

services:
  chaynsapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chaynsapi
    restart: unless-stopped
    ports:
      - "${PORT:-5555}:${PORT:-5555}"
    environment:
      - USER_TOBIT_ID=5139275
      - BEARER_TOKEN=Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsInZlciI6MSwia2lkIjoibmt5M21kYmcifQ.eyJqdGkiOiJlMzkyY2E4Yi0xMjQ5LTQxZGYtOWJmZC02NzcxMmUzYWYyNTAiLCJzdWIiOiJYOFYtM1JTVTciLCJ0eXBlIjoxLCJleHAiOiIyMDI1LTAyLTA1VDEyOjA2OjIwWiIsImlhdCI6IjIwMjUtMDItMDFUMTI6MDY6MjBaIiwiTG9jYXRpb25JRCI6Mzc4LCJTaXRlSUQiOiI2MDAyMS0wODk4OSIsIklzQWRtaW4iOmZhbHNlLCJUb2JpdFVzZXJJRCI6NTEzOTI3NSwiUGVyc29uSUQiOiJYOFYtM1JTVTciLCJGaXJzdE5hbWUiOiJ5eCIsIkxhc3ROYW1lIjoieHkiLCJSb2xlcyI6WyJzd2l0Y2hfbG9jYXRpb24iXSwicHJvdiI6MH0.KBzY8csWc-zA-tkUGW2_8pNzNCnI9ljlKY_wUSQDjPU6mwoDZGLeAcaDY4CKRvtiUh6b3rj4-5vC7KHI0yVZS52cA1q6qG-ulh54EmDO7pm_A0J0LuGMZZ6ZHWfRomr06peAbWaM-UTvKYeAtvVdvwI7ZKsRG42M04HD8H4d11nX03Kq_xDUFPnkjooBOQgSqho-NeMLBioV_B1ruZrat4Y0oGR5fVpsOuyhjJ_oXWhfsPOHEbiNmqG2R850r2oH9juf8-bnE2kMhhg83DZVcPW9ri-yfuk_UYqcfIRikM3Yl4BCUy-gETUuA0w641VliM80A2YUZp9tiaVn9HPCUg
      - PORT=${PORT:-5555}
      - DEBUG=${DEBUG:-true}
      - MAX_ATTEMPTS=${MAX_ATTEMPTS:-30}
      - Delay=${Delay:-1} 
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5555}/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./logs:/app/logs  # 如果需要持久化日志
    networks:
      - chayns_network

networks:
  chayns_network:
    driver: bridge 